x-mongo-uri: &mongo-uri
  MONGO_URI: "mongodb://mongodb:27017"

services:
  stocks1-a:
    build:
      context: .
      dockerfile: ./Stocks/Dockerfile
    environment:
      <<: *mongo-uri
      COLLECTION_NAME: "stocks1"
    ports:
      - "5001:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb
    restart: always

  stocks1-b:
    build:
      context: .
      dockerfile: ./Stocks/Dockerfile
    environment:
      <<: *mongo-uri
      COLLECTION_NAME: "stocks1"
    ports:
      - "5004:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb
    restart: always

  stocks2:
    build:
      context: .
      dockerfile: ./Stocks/Dockerfile
    environment:
      <<: *mongo-uri
      COLLECTION_NAME: "stocks2"
    ports:
      - "5002:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb
    restart: always

  cap-gains:
    build:
      context: .
      dockerfile: ./CapitalGains/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - stocks1-a
      - stocks2
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      # expose this container to other containers
      - "27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  nginx:
    build: ./nginx
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
    ports:
      - "80:80"
    restart: always

volumes:
  mongo-data:
