apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-service
  namespace: stocks-manager
  labels:
    app: stocks-service
spec:
  replicas: 2 #two instances of the app
  selector:
    matchLabels:
      app: stocks-service
  template:
    metadata:
      labels:
        app: stocks-service
    spec:
      containers:
      - name: stocks-service
        image: stocks-service:latest
        ports:
        - containerPort: 8000

