apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-manager
spec:
  replicas: 2 #two instances of the app
  selector:
    matchLabels:
      app: stocks-manager
  template:
    metadata:
      labels:
        app: stocks-manager
    spec:
      containers:
      - name: stocks-manager
        image: stocks-manager:latest
        ports:
        - containerPort: 8000

