apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: stocks-manager
  labels:
    app: nginx
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        upstream stocks {
            server stocks-service:8000;
        }

        upstream capital-gains {
            server capital-gains-service:8000;
        }

        server {
            listen 80;
            
            server_name localhost;

            # Allow GET requests to /stocks and /stocks/{id} through NGINX
            location /stocks {
                proxy_pass http://stocks;
            }

            # Allow /kill requests to stocks service
            location /kill {
                proxy_pass http://stocks;
            }
            # Allow requests to /portfolio-value and /stocks-value through NGINX

            location /portfolio-value {
                proxy_pass http://stocks;
            }
            location /stock-value {
                proxy_pass http://stocks;
            }

            location /capital-gains {
                proxy_pass http://capital-gains;
            }

            location / {
                return 403;
            }
        }
    }
