apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: stocks-app
  labels:
    app: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        upstream stocks-backend {
            server stocks-manager-service:5000;  # Updated to match Service name
        }

        upstream capital-gains-backend {
            server capital-gains-service:5000;  # Ensure this service exists
        }

        server {
            listen 80;
            server_name localhost;

            location /stocks {
                proxy_pass http://stocks-backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /capital-gains {
                proxy_pass http://capital-gains-backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
