apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-manager
  namespace: stocks-app  # Added namespace to match ConfigMap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-manager
  template:
    metadata:
      labels:
        app: stocks-manager
    spec:
      containers:
      - name: stocks-manager
        image: <dockerhub-username>/stocks-manager:latest  # Replace with actual Docker image
        ports:
        - containerPort: 5000
