apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-manager-deployment
  namespace: stocks-app
  labels:
    app: stocks-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-manager
  template:
    metadata:
      labels:
        app: stocks-manager
    spec:
      containers:
      - name: stocks-manager
        image: stocks-manager:latest
        ports:
        - containerPort: 5000
        volumeMounts:  # Mount the PVC to the container
        - name: stocks-manager-volume
          mountPath: /app/data  # Application's data directory
      volumes:
      - name: stocks-manager-volume
        persistentVolumeClaim:
          claimName: stocks-manager-pvc  # References the PVC
