apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: stocks-manager # Matches the namespace of the deployment
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Matches the PV size
  storageClassName: standard  # Ensure this matches the PV
