apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: stocks-manager  # Ensure this matches the namespace of the deployment
  labels:
    app: mongodb  # Updated label to match the deployment
spec:
  capacity:
    storage: 1Gi  # Adjust as needed
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/mongodb  # Updated path to match the stocks-manager application
