apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: stocks-manager  # Add namespace to match your deployment
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb